---
stages:
  - review
  - validate
  - init
  - plan
  - deploy
  - verify

set_deploy_env:stage:
  stage: review
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - echo "ENV=stage" >> review.env
  artifacts:
    reports:
      dotenv: review.env

set_deploy_env:prod:
  stage: review
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "ENV=prod" >> review.env
  artifacts:
    reports:
      dotenv: review.env

tf_validate:
  stage: validate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs: 
    - job: set_deploy_env:stage
      optional: true
    - job: set_deploy_env:prod
      optional: true
  image:
    name: "hashicorp/terraform:1.2.2"
    entrypoint: [""]
  script:
    - terraform init -backend-config=config.s3.backend.tfvars
    - terraform validate
    - terraform fmt -check=true

init_workspace:
  stage: init
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
  needs: 
    - job: set_deploy_env:stage
      optional: true
    - job: set_deploy_env:prod
      optional: true
  image:
    name: "hashicorp/terraform:1.2.2"
    entrypoint: [""]
  script:
    - terraform init -backend-config=config.s3.backend.tfvars
    - terraform workspace new $ENV

tf_plan:
  stage: plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs: 
    - job: set_deploy_env:stage
      optional: true
    - job: set_deploy_env:prod
      optional: true
    - job: tf_validate
    - job: init_workspace
  image:
    name: "hashicorp/terraform:1.2.2"
    entrypoint: [""]
  script:
    - terraform init -backend-config=config.s3.backend.tfvars
    - terraform workspace select $ENV
    - terraform plan  -var-file=common.tfvars -var-file=$ENV.env.tfvars -out plan
  artifacts:
    name: plan
    paths:
      - plan

tf_apply:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs:
    - job: set_deploy_env:stage
      optional: true
    - job: set_deploy_env:prod
      optional: true
    - job: tf_plan
  image:
    name: "hashicorp/terraform:1.2.2"
    entrypoint: [""]
  script:
    - terraform init -backend-config=config.s3.backend.tfvars
    - terraform workspace select $ENV
    - terraform apply plan

verify:
  stage: verify
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs:
    - job: set_deploy_env:stage
      optional: true
    - job: set_deploy_env:prod
      optional: true
    - job: tf_apply
  image:
    name: "shdu/pyats-genie:latest"
    entrypoint: [""]
  script:
    - cd tests
    - source /pyats/bin/activate
    - pyats run job test_job.py -t $ENV.yml
